[package]
name = "wl-actions"
version = "0.1.0"
edition = "2024"

[dependencies]
wl-proxy = { path = "../../wl-proxy", features = ["all-protocols"] }
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
thiserror = "2.0"
error_reporter = "1.0"
ctrlc = "3.4"
